### ISSUE TITLE
Where‘s the PlusPoint repository?

### ISSUE THREAD

**Issue by Ein-Tim** [FidelisFactory/FidelisFactory.github.io#5]
The PlusPoint app links to https://github.com/FidelisFactory/PlusPoints, however, that‘s a 404. Where‘s the repo?

**Comment by fechu** [comment]
The link is correct, but the repo is currently private while we clean up some code before open sourcing it. 

Would you like to contribute or do you have any other question we can answer?

**Comment by Ein-Tim** [comment]
@fechu 

Thanks for the fast response! I was just curious, no concrete questions or remarks at the moment!

Thanks for this great app!
